[workspace]
resolver = "3"
members = [
    "common/device",
    "common/connection",
    "ares-package",
    "ares-install",
    "ares-push",
    "ares-launch",
    "ares-device",
    "ares-shell",
    "ares-setup-device",
    "ares-novacom",
    "ares-pull",
]

[workspace.package]
version = "0.5.0"
edition = "2024"
license = "Apache-2.0"
authors = ["Mariotaku <git@mariotaku.me>"]
repository = "https://github.com/webosbrew/ares-cli-rs"
homepage = "https://github.com/webosbrew/ares-cli-rs"
keywords = ["webos", "lg", "cli"]
categories = ["command-line-utilities"]

[profile.release]
strip = true

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
upper_case_acronyms = "allow"

[workspace.dependencies]
# Internal libraries. Both path and version are needed: path for local builds,
# version for `cargo publish`.
ares-device-lib = { path = "common/device", version = "0.5.0" }
ares-connection-lib = { path = "common/connection", version = "0.5.0" }
clap = { version = "4.4.6", features = ["derive", "env"] }
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
libssh-rs = "0.3.8"
libssh-rs-sys = { version = "0.2.8", default-features = false }
sha256 = "1.5.0"
regex = "1.11.1"
indicatif = "0.17.8"
httparse = "1.10.1"
