[package]
name = "ares-shell"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Open an interactive shell on a webOS device"

[lints]
workspace = true

[dependencies]
ares-device-lib = { workspace = true }
ares-connection-lib = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
libssh-rs = { workspace = true }
crossbeam-channel = "0.5.15"
crossterm = "0.29.0"
rustyline = { version = "15.0.0", default-features = false }

[package.metadata.deb]
section = "devel"
