[package]
name = "ares-setup-device"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Add, change or remove webOS devices"

[lints]
workspace = true

[dependencies]
ares-device-lib = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
serde_json = { workspace = true }

[package.metadata.deb]
section = "devel"
