[package]
name = "ares-install"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Install or remove an app on a webOS device"

[lints]
workspace = true

[dependencies]
ares-device-lib = { workspace = true }
ares-connection-lib = { workspace = true }
clap = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
libssh-rs = { workspace = true }
sha256 = { workspace = true }
regex = { workspace = true }
indicatif = { workspace = true }

[package.metadata.deb]
section = "devel"
