[package]
name = "ares-novacom"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Low-level device transport helpers (SSH key retrieval, port forwarding)"

[lints]
workspace = true

[dependencies]
ares-device-lib = { workspace = true }
ares-connection-lib = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
libssh-rs = { workspace = true }

[package.metadata.deb]
section = "devel"
